### ISSUE TITLE
How are you growing as a developer?

### ISSUE THREAD

**Issue by iamakulov** [mxstbr/ama#1]
You’re just 19, and your achievements are already pretty cool: 3K:star:-project, a thousand of followers at Twitter, membership in [React Community](https://github.com/reactjs), a bunch of talks and probably something else I don’t know. How’ve you got here at 19 (I believe you should’ve been programming since the middle school?) and how many time do you spend on all this stuff?

**Comment by mxstbr** [comment]
That's a very good question :+1: that I want to answer as thoroughly as possible – give me a few days to respond! Thanks!

**Comment by mxstbr** [comment]
This essentially boils down to two things: _passion_ and _privilege_.

**Passion**

_I love coding_. I get up in the morning, boot my Mac and start programming. I think about code (almost) 24/7 and have my editor open and actually write code between 4 and 12 hours per day, every day. When I'm out and about, I read articles about coding, follow the news on Twitter (highly recommend being active on Twitter to every developer), volunteer at conferences (thanks to [Joschi](https://twitter.com/jkphl) for introducing me to that) and stuff like that. Not because I have to, but because I cannot imagine a more interesting thing to do!

I did a bit of programming in high school, but only very basic HTML, CSS and bash scripting. That basic HTML and CSS landed me an internship at [Animade](http://animade.tv) in London after high school graduation. I spent three months (Jan–Apr 2015) there, learning more advanced HTML, CSS, basic JavaScript and in the end this cool new thing called "React.js". Since then I've worked as a freelancer! (until this week, see #2)

**Privilege**

None of this would matter were it not for the very privileged position I'm in. Next to my general privileged position as a white upper-middle class male, I didn't have to work for the past ± year thanks to my parents paying everything. Instead, I could spent my days programming and learning, which was a huge factor to being where I am now and I am _very_ grateful for. This is not a luxury many people have and I'm trying to help other people in less fortunate positions as much as I can.

I hope that answer the questions!

---

Addendum:

_(Breaking the fourth wall now, Underwood style)_

If you're reading this and want to become a developer, there's two main, practical tips I have for you:
1. Be active in the community. This includes talking to people on Twitter, going to conferences (if you can't afford it, volunteer!), going/organising meetups,...
2. Share what you do. Post every bit of code you write online, write blog posts (I suck at that...) and share what you learn every day no matter how basic,...

If you do those things, provided you're passionate about coding and have enough time and space to learn it, you'll have a good time.

**Comment by mxstbr** [comment]
Also, because you specifically mention my membership in the `reactjs` Github organisation. That is not some sort of elitist club, not at all. Start watching the repositories you're interested in (for me that was Redux, reselect,...) and when a new question comes up in the issues try to answer it to the best of your ability.

It doesn't necessarily matter if the answer is 100% correct or not as long as you're friendly and humble. Overtime you'll find opportunities from reading all issues to open PRs to fix bugs and after a while somebody will trust you enough to add you to the org. **Everybody can be part of it!**
