### ISSUE TITLE
What's your development set up?

### ISSUE THREAD

**Issue by sotojuan** [mxstbr/ama#11]

**Comment by mxstbr** [comment]
**My current setup:** (last updated 2018-05-14)

- Retina MacBook Pro from 2017
- External Apple Touchpad (I don't like mice for Apple stuff, the touchpads are tooo goooood)
- Kinesis Advantage Pro ergonomic keyboard, long-term loaned from @michaelglass (thaaanks)
- Dell 24" secondary monitor
- OneHome monitor stand
- RoostStand laptop stand (I have my laptop next to my Dell monitor so it's a two-monitor setup)
- Bose QuietComfort (QC) 35 in-ear headphones
- Swan M10 speakers in white

<details>
  <summary>Click to see replaced parts from 2016</summary>

  - Retina MacBook Pro from Late-2013 running OS X 10.11
  - [DasKeyboard](http://www.amazon.de/gp/product/B00KA4H3CY/ref=as_li_tl?ie=UTF8&camp=1638&creative=6742&creativeASIN=B00KA4H3CY&linkCode=as2&tag=reddit0e-21) mechanical keyboard with brown switches
- [Audio-technica ATH-M50X](http://www.amazon.de/gp/product/B00HVLUR86/ref=as_li_tl?ie=UTF8&camp=1638&creative=6742&creativeASIN=B00HVLUR86&linkCode=as2&tag=reddit0e-21) headphones (when I'm in an office)

</details>

**Comment by k15a** [comment]
Hey Max, how much RAM do you have in your MacBook?

**Comment by mxstbr** [comment]
16GB, though it's starting to become slow for some reason, so I'm getting a 13" new MacBook Pro with TouchBar soon!

I've since the original answer also gotten a Synology NAS with four 1TB HDDs, which both my MacBook and my Android phone automatically backup to. I might write a blog post about that in the future... (want that? Give this comment a :+1: so I know!)

**Comment by k15a** [comment]
I know that :) I have 8GB RAM and can't use Atom or Hyper because of that. Probably the reason why I don't like all the new Electron apps because they are so memory hungry and not everybody can upgrade their device so often.

Would love to see such a blog post as I am thinking about getting one myself too. Could you also share why you went with Synology and not with another company?

**Comment by mxstbr** [comment]
> Could you also share why you went with Synology and not with another company?

Good marketing, I guess ¯\\\_(ツ)\_/¯ no particular reason other than "it works"™️

I got the DS414slim with 4 WD 10JFCX 1TB 2.5" HDDs. This is a really good series about setting up a NAS, targeted at photographers but well worth the read for anybody getting a NAS: https://paulstamatiou.com/storage-for-photographers-part-2/

*Sadly only found it after I had bought mine, but now I'd probably also get the DS415+ since the DS414slim only holds 2.5" HDDs which are limited to 1TB right now. The DS415+ can hold normal size HDDs, so you can fit 3TB ones in too! Much more space...*

**Comment by mxstbr** [comment]
I've updated my comment above with my setup changes, here's the summary:

- Upgraded to a new MBP
- Switched from the DasKeyboard to an ergonomic Kinesis Advantage Pro, would highly recommend to go ergonomic if you can (shoutout to @michaelglass for loaning me his Kinesis)
- Switched from my over-ear AudioTechnicas to in-ear noise cancelling Bose QC35s
