### ISSUE TITLE
Education and work

### ISSUE THREAD

**Issue by iamakulov** [mxstbr/ama#2]
Do you study somewhere? Do you work somewhere?

**Comment by mxstbr** [comment]
I just started doing both of those things actually:
- I'm studying Philosophy at the [University of Vienna](http://www.univie.ac.at/en/)
- I work remotely at [Thinkmill](http://thinkmill.com.au) as their first fulltime open source developer since the beginning of this week! :tada: I mainly focus on [Keystone](https://github.com/keystonejs/keystone) and making it the best (Node.js) content management platform ever.

**Comment by iamakulov** [comment]
Great, congratulations on the new job!

**Comment by johannesnagl** [comment]
congrats!

**Comment by mxstbr** [comment]
Thanks!

**Comment by vnglst** [comment]
Kind of a follow up question (should I open a new one?). Why did you choose to study Philosophy and not Computer Science (i.e. Informatik)?

Disclaimer: I majored in Philosophy, but I'm now pursuing a career as a developer.

**Comment by mxstbr** [comment]
Congrats on the 89 day streak, that pursuit is going quite well apparently!

I did try to study CompSci twice, but left both times after a few months because it had nothing to do with my interests. CompSci and frontend development are after the introductory-general-programming-language-stuff (if-else, loops, recursion, etc.) unrelated for the most part.

There a few things (algorithms, database modelling) that would've been helpful, but I felt it wasn't worth it to spend three to five years fighting with 95% of courses that weren't interesting just for the 5% juicy bits – I'd rather just learn those 5% on my own and skip the annoying 95%!

**Comment by brotzky** [comment]
> CompSci and frontend development are after the introductory-general-programming-language-stuff (if-else, loops, recursion, etc.) unrelated for the most part.
> 
> I'd rather just learn those 5% on my own and skip the annoying 95%

100% agreed on this point, @mxstbr

**Comment by glennreyes** [comment]
Congrats! ;)

**Comment by siddharthkp** [comment]
@vnglst @mxstbr, we should make a clan of non computer science devs!
