### ISSUE TITLE
What is you vision of Javascript's future?

### ISSUE THREAD

**Issue by amilajack** [mxstbr/ama#21]
* What is a feature that you think should be part of JS in the future?
* What is the next big step in Javascript tooling?

**Comment by mxstbr** [comment]
Optional Static Typing.

JavaScript as a language is super easy to get into because it doesn't have any types. Beginners don't need to understand complex Computer Science-y things they don't care about, they can just write code. No need to understand the nitty-gritty to get anything done.

With other languages that's not the case, e.g. in my experience, to build something in Java you have to understand a bunch of stuff you don't care about, like classes, modules, and types. It's a big hurdle, and part of the reason why JS is so popular is because it's super easy to get into.

----

The thing is that static typing actually make writing code more _fun_ once you know what you're doing. That's a pretty subjective call obviously, but with a good IDE writing statically typed code makes everything easy. You avoid many stupid mistakes, immediately get feedback about potential issues, don't need to dig into docs to use a library, etc.

It's fun!

Now, JavaScript by default I don't think will ever have types. It's way too far spread and way too popular to do such a fundamental change. Buuuut I recently read Guido van Rossum (creator and BDFL of Python) is [working on or has added optional static types to Python recently](https://twitter.com/gvanrossum/status/809806689134182400)!

So now I'm pretty convinced we'll go down this route eventually and have optional static typing in JavaScript. (ES2025?!)
