### ISSUE TITLE
How does your desk looks like?

### ISSUE THREAD

**Issue by k15a** [mxstbr/ama#23]
A picture would be great 🖥

**Comment by mxstbr** [comment]
I wanted to send a picture here a while ago but totally forgot! Can you remind me in a week or so? I'm currently travelling.

**Comment by k15a** [comment]
Hey, AFAIK you're now back home. Here is your reminder 😜
How was React in Flip Flops?

**Comment by mxstbr** [comment]
![desk](https://cloud.githubusercontent.com/assets/7525670/23694905/cee211ce-03dc-11e7-9184-36cda7a9f415.jpg)

Thanks for the reminder, here you go! (finally..)

RiFF was amazing, if exhausting. Teaching a week-long bootcamp is basically like doing three conferences, except you have every talk and Q&A slot instead of just one. Very rewarding though, seeing the stuff people built at the end after just 6 short days was impressive and inspiring and made it totally worth it 👌

**Comment by k15a** [comment]
Thank you. I have this lamp as well 🎉 Did you saw it on Jonathan Morrison's YouTube channel?

**Comment by mxstbr** [comment]
I did, haha!

**Comment by hugomd** [comment]
@mxstbr Do you like your Kinesis Advantage? I've been thinking about getting one, but they're so expensive!

Also — is that a magic trackpad 2?

**Comment by mxstbr** [comment]
Yes and no. It's super nice to type on, but it's also a bit of a pain in the ass because keyboard shortcuts are super inaccessible. 

I'd recommend getting an ergonomic keyboard, but I don't know if I'd recommend getting that specific one. Have to try some others! 

And yes, that is a magic trackpad 2 I think.
