### ISSUE TITLE
Burning out

### ISSUE THREAD

**Issue by iamakulov** [mxstbr/ama#3]
According to https://github.com/mxstbr/ama/issues/1#issuecomment-207999311, you work quite a lot. How do you keep yourself from burning out? Have you ever experienced a burnout?

**Comment by mxstbr** [comment]
Good question! I haven't, thankfully. Right now, I really really enjoy coding and only do it that much because I love it.

Once I stop loving it, I don't know what I'll do! Hopefully that time never comes, but if does, maybe travelling somewhere completely secluded from the internet for a long-ish period of time might help.

**Comment by koresar** [comment]
I burn out at the age of 29.  You have plentiful of time mate. ☺

**Comment by mxstbr** [comment]
@koresar are you still burnt out? If not, what did you do to combat it?

**Comment by koresar** [comment]
Decreased this
"write code between 4 and 12 hours per day, every day"
to be more like 40 h/week.
Distract mind from coding.
Some meditation.

The recipe depends and vary for other people.
