### ISSUE TITLE
What's the deal with Ugmonk Ampersand Hoodie?

### ISSUE THREAD

**Issue by panalbish** [mxstbr/ama#30]
I found it quite often that, most of the time you wear [Red Ugmonk Ampersand Hoodie](http://www.quenchandconquer.com/style/ugmonk-premium-ampersand-crewneck/) (actually on all your conf/meetup talks I have seen). 

P.S: BTW, it looks good 👍

**Comment by mxstbr** [comment]
> Sidenote: My sweater now has its own Twitter account to share the good times! Follow [@mxswtr](https://twitter.com/mxswtr) to see all the pictures of me and my sweater 😂 (Sidenote: I have no idea who made or owns that account, it's not me!)

**World Premiere: The Full Story of Max' Sweater**

In case you're reading this but have no idea which sweater we're talking about, this is it:

<img alt="Max speaking at VoxxedDays Thessaloniki in his red sweater"
 src="https://cloud.githubusercontent.com/assets/7525670/23504803/e823dbca-ff38-11e6-9119-e3d1bd240a5c.jpg" height="400px" />

About three (?) years ago I stumble upon [Ugmonk](http://ugmonk.com). I browse through their site and find this gorgeous, red sweater with a white ampersand on the front. Living in Vienna, buying it is prohibitively expensive (with shipping and taxes ~80-100EUR), so the idea of buying it is shelved as a "Once I'm rich...".

A year later I still haven't stopped thinking about that sweater. (the number of times I visited the page must've been in the hundreds) Finally I go "Fuck it, I like it so much so it's worth buying.". Together with a [Grey Mountain Cap](http://shop.ugmonk.com/products/mountains-baseball-cap-black) (which also gets a ton of wear, just not to tech events) the order is placed and arrives a few weeks later at my doorstep.

I start wearing the sweater, and since it's the nicest one I have I tend to wear it to events and when I meet folks in a "professional" (programming) context. (I have about 4 or 5 other ones too, but they're not _as_ awesome)

About a year ago I start speaking at conferences and giving public appearances. After a while folks begin to recognise me based on the sweater, they come up to me and go "I know that sweater—you must be Max!". It turns into a "trademark" of sorts, which only entices me more to wear it to events!

----

That's the full story of my sweater which has never been told before! To answer the two most common questions I get asked about it:

- Yes, I only have one (Want to make me really happy? Send me a second one!)
- Yes, it does get washed often. Even though the images make it seem that way, I only wear it ~twice a week, and on the other days it's either washing or drying.

**Comment by jolyonruss** [comment]
Godamnit Max, now I have a bunch of t-shirts I want to buy!

Also, it looks like they don't have SSL setup on all of their site - so the link to https://ugmonk.com is broken, but http://ugmonk.com works

**Comment by franzdumfart** [comment]
FINALLY!!!!

**Comment by dervondenbergen** [comment]
I strongly believe @timarney is your sweater, as it only follows [Ugmonk](http://ugmonk.com), you and him 🤔

**Comment by panalbish** [comment]
@mxstbr : Thanks for your detail answer. Ok let me check the Ugmonk website now 🛍  😄

**Comment by mxstbr** [comment]
**Update**

The sweater now has a blue brother, courtesy of Ugmonk! After seeing how much wear I get out of my current one they graciously reached out and sent me another one:

![sweater](https://cloud.githubusercontent.com/assets/7525670/25420668/75faa1c2-2a59-11e7-8ae1-9465765c2c1c.jpg)

> Note: I could've gone for another red one, but I think people wouldn't stop asking me how many I have so now there's a blue one and a red one. Gotta catch them all, only grey and black remaining! 😉

**Comment by Maybach91** [comment]
Thanks to https://x.com/benjaminsehl/status/1912923186678665375 i stumbled across this beautiful liveable art performance.
