### ISSUE TITLE
How do common shared styles fit in with styled components?

### ISSUE THREAD

**Issue by chhuang** [mxstbr/ama#34]
Such as CSS grids and typography.

**Comment by mxstbr** [comment]
I'd challenge you to think about the shared styles you need in your app. There is probably a CSS reset (can still use that with styled-components perfectly fine), then there's typography and maybe a grid. 

Rather than having a global .grid class, why not make a <Grid /> component? Take a look at github.com/jsbros/hedron for example! 

The same thing goes for typography, rather than styling global tags I have components for <Heading />, <Text /> etc. Makes the whole codebase super easy to understand and follow!

**Comment by mxstbr** [comment]
Sidenote, if you really truly want global styles you can use `injectGlobal`, but we don't recommend it. See: https://github.com/styled-components/styled-components/blob/master/docs/api.md#injectglobal

**Comment by chhuang** [comment]
So with styled components, there is no need for global styles at all? Sorry, I'm still trying to understand the basic concept.

So instead of: `p { font-family: Helvetica; }`, I'd need to have `font-family: Helvetica` for every single component?
