### ISSUE TITLE
What's your favorite ski resort 

### ISSUE THREAD

**Issue by sebastiandeutsch** [mxstbr/ama#37]

**Comment by mxstbr** [comment]
This is a hard question because I haven't been at many! My family had a lodge at a tiny ski resort called Lachtal in Austria, so that's where we went every winter for the past 19 years or so. 

I really enjoyed Jackson Hole when I went there with @nikgraf, skiing in America is a completely different experience. It's basically one huge mountain with a handful "groomed slopes", but most of the time you just go straight through forest and find your way down. 

I also really enjoyed Arlberg when we went there for AgentConf. I mean, who can argue with heli skiing?! https://twitter.com/mxstbr/status/823938714346934277

So the TL;DR is, I haven't been to many, want to go to more of them in the future 😎
