### ISSUE TITLE
Use cases where styled-components is not the right choice?

### ISSUE THREAD

**Issue by robbue** [mxstbr/ama#45]
_First of all, thanks for all your amazing work on react-boilerplate and styled-components. It has been a great starting point for me and my colleagues!_

[styled-components](https://github.com/styled-components/styled-components) is described as "visual primitives for the component age". After using it for a couple of projects, it's does that very well.

Do you find any use cases where styled-components _is not_ the right choice?

My question are a bit of a leading question, because recently while doing a custom campaign site I found that it took me much longer to write markup and styles with SC because there was few reusable components, like there usually is on regular websites.
Creating single components for every element is time consuming, and in a larger project it would be time saving in the long run, but not for a small project. I could do the following, but that does not feel right.
```javascript
import { Wrapper, Sidebar, Footer } from 'styles';
```

 It would be interesting to hear your opinions as one of the creators of SC.

**Comment by mxstbr** [comment]
The main use case that styled-components is not great at is highly dynamic styles. If you have something that changes multiple times a second and you want to update some styles based on that change it's much faster to do it inline:

```JS
const Slow = styled.div`
  background: ${props => props.bg};
`

// vs.

<div style={{ background: bg }} />
```

That's because we have to inject the CSS everytime something changes and that's slower (for a single element doing it over and over and over) than attaching a single inline style.

----

I answered the question about why I think this structure actually works out perfectly well for shared components on StackOverflow a week ago or so, so I'll just refer to that answer: https://stackoverflow.com/questions/42987939/styled-components-organization
