### ISSUE TITLE
What does your home coffee/espresso setup look like?

### ISSUE THREAD

**Issue by dennis-johnson-dev** [mxstbr/ama#46]
I saw some [amazing latte art](https://twitter.com/mxstbr/status/851438839457624066) and was curious which machine you're using to brew such fine art?

Cheers!

**Comment by mxstbr** [comment]
My setup is:

- La Spaziale Mini Vivaldi II machine
- Mazzer Mini grinder

<details>

<summary>Click to see pictures of me making coffee</summary>

<img src="https://cloud.githubusercontent.com/assets/7525670/25009523/3b1ab1f6-2067-11e7-9425-896a7092b1b4.jpg" width="30%" align="left" />

<img src="https://user-images.githubusercontent.com/7525670/36303849-da3c33ce-130d-11e8-9075-098d289622ab.jpg" width="30%" align="left" />

<img src="https://user-images.githubusercontent.com/7525670/36303837-ce27aa14-130d-11e8-81d3-fb7985ec9ed9.jpg" width="30%" align="left" />

</details>

<p align="left">
The Mini Vivaldi is one of the cheapest double boiler machines and works really well. (the one annoying thing is that La Spaziale has smaller group heads, 53mm vs the standard 58mm, which means I can't use VST precision baskets :cry:)

There's a really great hack with the grinder, the next bigger (and better) model from Mazzer is the Super Jolly. You can take Super Jolly burrs and put them into the Mini, and you basically have the Super Jolly for much less money! (the only difference other than the burrs is that the Super Jolly has more motor power, which I don't care about)
</p>

**Comment by mxstbr** [comment]
I recently improved my setup by creating a dedicated wall niche for my coffee stuff and hanging two prints:

![D0KzLLWWoAAoH6c](https://user-images.githubusercontent.com/7525670/54475407-53323300-47f1-11e9-91b2-19273302ad63.jpeg)

😍

**Comment by kafui4k** [comment]
beautiful, hoping to get a set up like this soon. and cant wait to open my first Cafe

**Comment by victorfds** [comment]
It's Amazing, @mxstbr .  
:coffee:

**Comment by mxstbr** [comment]
I've kept upgrading my setup since 2019! As of two weeks ago, it consists of:

- [Nuova Simonelli Mythos Clima Pro](https://simonelliusa.com/products/ns-mythos-grinder.asp) grinder
- [La Marzocco Linea Mini](https://international.lamarzocco.com/en/machine/linea-mini/) espresso machine

Completely overkill for a home setup, but incredibly awesome.

![37D939F6-7FE4-49C2-9B42-5B50B6868248](https://user-images.githubusercontent.com/7525670/145674964-3aeb9aae-c4b8-4659-bfe8-c63ebf6ac431.JPG)

**Comment by bkjoel** [comment]
The 'drooling' emoji is missing from the emoji reactions just for that setup picture! i'll have it here - 🤤 
Why did you pick the Nuova Simonelli Mythos Clima Pro grinder? first time I've seen it I have to admit, many go the single-dosing route with the Niche Zero from what I've seen
Also - I see that you're using the stock tamper, have you seen spring loaded tampers like normcore? some are also leveled on top of the portafilter which is real neat!
Awesome setup once again!

**Comment by mxstbr** [comment]
I recently moved to San Francisco and decided to sell my Linea Mini + Mythos instead of trying to move them halfway around the world. 🥲

However, no need to feel bad for me: I just got my new Decent + Sette 270wi setup here! 😍 

![A Decent Espresso machine next to a Baratza Sette 270wi grinder in a kitchen](https://github.com/mxstbr/ama/assets/7525670/ea784732-c714-4452-a5a7-63c948717d68)

This is a very different setup from my last one. The Linea + Mythos combination was a "This will reliably make good coffee and last forever." The Decent machine makes this more of an "I want to experiment and have fun exploring coffee and try to make exceptionally great cups."

Can't wait to dive in!
