### ISSUE TITLE
What are your daily habits/routines? 

### ISSUE THREAD

**Issue by AntonNiklasson** [mxstbr/ama#58]

**Comment by mxstbr** [comment]
I honestly don't have too many! I travel so much it's hard for me to get into any sort of routine, because every other week it's destroyed again by me not being at home 😅 

I guess the only real routine I have is my daily morning coffee. Every morning I get up and make coffee for myself and my girlfriend with my espresso machine! (#46) It's something I cherish because I really enjoy making good coffee and tinkering around with the recipe, temperature and whatnot is a lot of fun.
