### ISSUE TITLE
You once said, "... nobody has a clue what they're doing". Do you still feel this way? I know I do. 

### ISSUE THREAD

**Issue by brotzky** [mxstbr/ama#8]
😎✌️

**Comment by mxstbr** [comment]
Yeah, I think it's important for newcomers to understand that really, nobody has a fucking clue what the hell they're doing. Everybody is faking it to a certain extent, and I think it's important to not let [Impostor Syndrome](https://en.wikipedia.org/wiki/Impostor_syndrome) creep up on you. There's a reason you are where you are, do your best work and you'll be fine.

To be clear, I don't think I'm a good programmer. I have a tiny subset of knowledge I'm alright at, but outside of it—void. Even inside of that tiny subset I'm not the most knowledgeable person! That's fine though, and it drives me to learn new things every day. (One of the reasons I love the new job, #2, was that I can work on backend stuff instead of "just" doing frontend)

_I'll have to dig up that rant again from the Reactiflux logs..._

**Comment by mxstbr** [comment]
Posted this in a slightly more eloquent form as [an article](https://medium.com/@mxstbr/nobody-knows-what-the-fuck-they-re-doing-b62945f88b0d) and talked about it on the [workingdraft podcast (german!)](http://workingdraft.de/259).
